export const HOTO_SERVEY_DATA_REQUEST = "HOTO_SERVEY_DATA_REQUEST";
export const HOTO_SERVEY_DATA_SUCCESS = "HOTO_SERVEY_DATA_SUCCESS";
export const HOTO_SERVEY_DATA_FAILED = "HOTO_SERVEY_DATA_FAILED";

export const HOTO_SERVEY_BLOCK_DATA_REQUEST = "HOTO_SERVEY_BLOCK_DATA_REQUEST";
export const HOTO_SERVEY_BLOCK_DATA_SUCCESS = "HOTO_SERVEY_BLOCK_DATA_SUCCESS";
export const HOTO_SERVEY_BLOCK_DATA_FAILED = "HOTO_SERVEY_BLOCK_DATA_FAILED";

//new hoto assest constans
//block
//block assets portfolio
export const HOTO_BLOCK_ASSET_PORTFOLIO_DATA_REQUEST = "HOTO_BLOCK_ASSET_PORTFOLIO_DATA_REQUEST";
export const HOTO_BLOCK_ASSET_PORTFOLIO_DATA_SUCCESS = "HOTO_BLOCK_ASSET_PORTFOLIO_DATA_SUCCESS";
export const HOTO_BLOCK_ASSET_PORTFOLIO_DATA_FAILED = "HOTO_BLOCK_ASSET_PORTFOLIO_DATA_FAILED";

// block-wise assets
export const HOTO_BLOCK_WISE_ASSET_DATA_REQUEST = "HOTO_BLOCK_WISE_ASSET_DATA_REQUEST";
export const HOTO_BLOCK_WISE_ASSET_DATA_SUCCESS = "HOTO_BLOCK_WISE_ASSET_DATA_SUCCESS";
export const HOTO_BLOCK_WISE_ASSET_DATA_FAILED = "HOTO_BLOCK_WISE_ASSET_DATA_FAILED";

//block Warehouse
export const HOTO_BLOCK_WAREHOUSE_DATA_REQUEST = "HOTO_BLOCK_WAREHOUSE_DATA_REQUEST";
export const HOTO_BLOCK_WAREHOUSE_DATA_SUCCESS = "HOTO_BLOCK_WAREHOUSE_DATA_SUCCESS";
export const HOTO_BLOCK_WAREHOUSE_DATA_FAILED = "HOTO_BLOCK_WAREHOUSE_DATA_FAILED";

//block Maintenance
export const HOTO_BLOCK_MAINTENANCE_DATA_REQUEST = "HOTO_BLOCK_MAINTENANCE_DATA_REQUEST";
export const HOTO_BLOCK_MAINTENANCE_DATA_SUCCESS = "HOTO_BLOCK_MAINTENANCE_DATA_SUCCESS";
export const HOTO_BLOCK_MAINTENANCE_DATA_FAILED = "HOTO_BLOCK_MAINTENANCE_DATA_FAILED";

//block transfer
export const HOTO_BLOCK_REPLACEMENT_DATA_REQUEST = "HOTO_BLOCK_REPLACEMENT_DATA_REQUEST";
export const HOTO_BLOCK_REPLACEMENT_DATA_SUCCESS = "HOTO_BLOCK_REPLACEMENT_DATA_SUCCESS";
export const HOTO_BLOCK_REPLACEMENT_DATA_FAILED = "HOTO_BLOCK_REPLACEMENT_DATA_FAILED";

//block Transefer
export const HOTO_BLOCK_TRANSFER_DATA_REQUEST = "HOTO_BLOCK_TRANSFER_DATA_REQUEST";
export const HOTO_BLOCK_TRANSFER_DATA_SUCCESS = "HOTO_BLOCK_TRANSFER_DATA_SUCCESS";
export const HOTO_BLOCK_TRANSFER_DATA_FAILED = "HOTO_BLOCK_TRANSFER_DATA_FAILED";

//GP
//gp assets portfolio
export const HOTO_GP_ASSET_PORTFOLIO_DATA_REQUEST = "HOTO_GP_ASSET_PORTFOLIO_DATA_REQUEST";
export const HOTO_GP_ASSET_PORTFOLIO_DATA_SUCCESS = "HOTO_GP_ASSET_PORTFOLIO_DATA_SUCCESS";
export const HOTO_GP_ASSET_PORTFOLIO_DATA_FAILED = "HOTO_GP_ASSET_PORTFOLIO_DATA_FAILED";

// gp-wise assets
export const HOTO_GP_WISE_ASSET_DATA_REQUEST = "HOTO_GP_WISE_ASSET_DATA_REQUEST";
export const HOTO_GP_WISE_ASSET_DATA_SUCCESS = "HOTO_GP_WISE_ASSET_DATA_SUCCESS";
export const HOTO_GP_WISE_ASSET_DATA_FAILED = "HOTO_GP_WISE_ASSET_DATA_FAILED";

//block Warehouse
export const HOTO_GP_WAREHOUSE_DATA_REQUEST = "HOTO_GP_WAREHOUSE_DATA_REQUEST";
export const HOTO_GP_WAREHOUSE_DATA_SUCCESS = "HOTO_GP_WAREHOUSE_DATA_SUCCESS";
export const HOTO_GP_WAREHOUSE_DATA_FAILED = "HOTO_GP_WAREHOUSE_DATA_FAILED";

//block Maintenance
export const HOTO_GP_MAINTENANCE_DATA_REQUEST = "HOTO_GP_MAINTENANCE_DATA_REQUEST";
export const HOTO_GP_MAINTENANCE_DATA_SUCCESS = "HOTO_GP_MAINTENANCE_DATA_SUCCESS";
export const HOTO_GP_MAINTENANCE_DATA_FAILED = "HOTO_GP_MAINTENANCE_DATA_FAILED";

//block transfer
export const HOTO_GP_REPLACEMENT_DATA_REQUEST = "HOTO_GP_REPLACEMENT_DATA_REQUEST";
export const HOTO_GP_REPLACEMENT_DATA_SUCCESS = "HOTO_GP_REPLACEMENT_DATA_SUCCESS";
export const HOTO_GP_REPLACEMENT_DATA_FAILED = "HOTO_GP_REPLACEMENT_DATA_FAILED";

//block Transefer
export const HOTO_GP_TRANSFER_DATA_REQUEST = "HOTO_GP_TRANSFER_DATA_REQUEST";
export const HOTO_GP_TRANSFER_DATA_SUCCESS = "HOTO_GP_TRANSFER_DATA_SUCCESS";
export const HOTO_GP_TRANSFER_DATA_FAILED = "HOTO_GP_TRANSFER_DATA_FAILED";



//warehouse
//gp assets portfolio
export const HOTO_WAREHOUSE_ASSET_PORTFOLIO_DATA_REQUEST = "HOTO_WAREHOUSE_ASSET_PORTFOLIO_DATA_REQUEST";
export const HOTO_WAREHOUSE_ASSET_PORTFOLIO_DATA_SUCCESS = "HOTO_WAREHOUSE_ASSET_PORTFOLIO_DATA_SUCCESS";
export const HOTO_WAREHOUSE_ASSET_PORTFOLIO_DATA_FAILED = "HOTO_WAREHOUSE_ASSET_PORTFOLIO_DATA_FAILED";

// gp-wise assets
export const HOTO_WAREHOUSE_WISE_ASSET_DATA_REQUEST = "HOTO_WAREHOUSE_WISE_ASSET_DATA_REQUEST";
export const HOTO_WAREHOUSE_WISE_ASSET_DATA_SUCCESS = "HOTO_WAREHOUSE_WISE_ASSET_DATA_SUCCESS";
export const HOTO_WAREHOUSE_WISE_ASSET_DATA_FAILED = "HOTO_WAREHOUSE_WISE_ASSET_DATA_FAILED";

//block Warehouse
export const HOTO_WAREHOUSE_WAREHOUSE_DATA_REQUEST = "HOTO_WAREHOUSE_WAREHOUSE_DATA_REQUEST";
export const HOTO_WAREHOUSE_WAREHOUSE_DATA_SUCCESS = "HOTO_WAREHOUSE_WAREHOUSE_DATA_SUCCESS";
export const HOTO_WAREHOUSE_WAREHOUSE_DATA_FAILED = "HOTO_WAREHOUSE_WAREHOUSE_DATA_FAILED";

//block Maintenance
export const HOTO_WAREHOUSE_MAINTENANCE_DATA_REQUEST = "HOTO_WAREHOUSE_MAINTENANCE_DATA_REQUEST";
export const HOTO_WAREHOUSE_MAINTENANCE_DATA_SUCCESS = "HOTO_WAREHOUSE_MAINTENANCE_DATA_SUCCESS";
export const HOTO_WAREHOUSE_MAINTENANCE_DATA_FAILED = "HOTO_WAREHOUSE_MAINTENANCE_DATA_FAILED";

//block transfer
export const HOTO_WAREHOUSE_REPLACEMENT_DATA_REQUEST = "HOTO_WAREHOUSE_REPLACEMENT_DATA_REQUEST";
export const HOTO_WAREHOUSE_REPLACEMENT_DATA_SUCCESS = "HOTO_WAREHOUSE_REPLACEMENT_DATA_SUCCESS";
export const HOTO_WAREHOUSE_REPLACEMENT_DATA_FAILED = "HOTO_WAREHOUSE_REPLACEMENT_DATA_FAILED";

//block Transefer
export const HOTO_WAREHOUSE_TRANSFER_DATA_REQUEST = "HOTO_WAREHOUSE_TRANSFER_DATA_REQUEST";
export const HOTO_WAREHOUSE_TRANSFER_DATA_SUCCESS = "HOTO_WAREHOUSE_TRANSFER_DATA_SUCCESS";
export const HOTO_WAREHOUSE_TRANSFER_DATA_FAILED = "HOTO_WAREHOUSE_TRANSFER_DATA_FAILED";





