export const HOTO_SERVEY_DATA_REQUEST = "HOTO_SERVEY_DATA_REQUEST";
export const HOTO_SERVEY_DATA_SUCCESS = "HOTO_SERVEY_DATA_SUCCESS";
export const HOTO_SERVEY_DATA_FAILED = "HOTO_SERVEY_DATA_FAILED";