export const PACKAGE_DROPDOWN_DATA_REQUEST = "PACKAGE_DROPDOWN_DATA_REQUEST";
export const PACKAGE_DROPDOWN_DATA_SUCCESS = "PACKAGE_DROPDOWN_DATA_SUCCESS";
export const PACKAGE_DROPDOWN_DATA_FAILED = "PACKAGE_DROPDOWN_DATA_FAILED";