// Block
//Maintainace
//Maintenance request
export const OANDM_BLOCK_MAINTENANCE_REQUEST_DATA_REQUEST =
  "OANDM_BLOCK_MAINTENANCE_REQUEST_DATA_REQUEST";
export const OANDM_BLOCK_MAINTENANCE_REQUEST_DATA_SUCCESS =
  "OANDM_BLOCK_MAINTENANCE_REQUEST_DATA_SUCCESS";
export const OANDM_BLOCK_MAINTENANCE_REQUEST_DATA_FAILED =
  "OANDM_BLOCK_MAINTENANCE_REQUEST_DATA_FAILED";
//request assign
export const OANDM_BLOCK_MAINTENANCE_REQUEST_ASSIGN_DATA_REQUEST =
  "OANDM_BLOCK_MAINTENANCE_REQUEST_ASSIGN_DATA_REQUEST";
export const OANDM_BLOCK_MAINTENANCE_REQUEST_ASSIGN_DATA_SUCCESS =
  "OANDM_BLOCK_MAINTENANCE_REQUEST_ASSIGN_DATA_SUCCESS";
export const OANDM_BLOCK_MAINTENANCE_REQUEST_ASSIGN_DATA_FAILED =
  "OANDM_BLOCK_MAINTENANCE_REQUEST_ASSIGN_DATA_FAILED";

//Replacement
//Replacement request
export const OANDM_BLOCK_REPLACEMENT_REQUEST_DATA_REQUEST =
  "OANDM_BLOCK_REPLACEMENT_REQUEST_DATA_REQUEST";
export const OANDM_BLOCK_REPLACEMENT_REQUEST_DATA_SUCCESS =
  "OANDM_BLOCK_REPLACEMENT_REQUEST_DATA_SUCCESS";
export const OANDM_BLOCK_REPLACEMENT_REQUEST_DATA_FAILED =
  "OANDM_BLOCK_REPLACEMENT_REQUEST_DATA_FAILED";
//request assign
export const OANDM_BLOCK_REPLACEMENT_REQUEST_ASSIGN_DATA_REQUEST =
  "OANDM_BLOCK_REPLACEMENT_REQUEST_ASSIGN_DATA_REQUEST";
export const OANDM_BLOCK_REPLACEMENT_REQUEST_ASSIGN_DATA_SUCCESS =
  "OANDM_BLOCK_REPLACEMENT_REQUEST_ASSIGN_DATA_SUCCESS";
export const OANDM_BLOCK_REPLACEMENT_REQUEST_ASSIGN_DATA_FAILED =
  "OANDM_BLOCK_REPLACEMENT_REQUEST_ASSIGN_DATA_FAILED";

//Transfer
//Transfer request
export const OANDM_BLOCK_TRANSFER_REQUEST_DATA_REQUEST =
  "OANDM_BLOCK_TRANSFER_REQUEST_DATA_REQUEST";
export const OANDM_BLOCK_TRANSFER_REQUEST_DATA_SUCCESS =
  "OANDM_BLOCK_TRANSFER_REQUEST_DATA_SUCCESS";
export const OANDM_BLOCK_TRANSFER_REQUEST_DATA_FAILED =
  "OANDM_BLOCK_TRANSFER_REQUEST_DATA_FAILED";
//request assign
export const OANDM_BLOCK_TRANSFER_REQUEST_ASSIGN_DATA_REQUEST =
  "OANDM_BLOCK_TRANSFER_REQUEST_ASSIGN_DATA_REQUEST";
export const OANDM_BLOCK_TRANSFER_REQUEST_ASSIGN_DATA_SUCCESS =
  "OANDM_BLOCK_TRANSFER_REQUEST_ASSIGN_DATA_SUCCESS";
export const OANDM_BLOCK_TRANSFER_REQUEST_ASSIGN_DATA_FAILED =
  "OANDM_BLOCK_TRANSFER_REQUEST_ASSIGN_DATA_FAILED";

//Scrap
//Scrap request
export const OANDM_BLOCK_SCRAP_REQUEST_DATA_REQUEST =
  "OANDM_BLOCK_SCRAP_REQUEST_DATA_REQUEST";
export const OANDM_BLOCK_SCRAP_REQUEST_DATA_SUCCESS =
  "OANDM_BLOCK_SCRAP_REQUEST_DATA_SUCCESS";
export const OANDM_BLOCK_SCRAP_REQUEST_DATA_FAILED =
  "OANDM_BLOCK_SCRAP_REQUEST_DATA_FAILED";
//request assign
export const OANDM_BLOCK_SCRAP_REQUEST_ASSIGN_DATA_REQUEST =
  "OANDM_BLOCK_SCRAP_REQUEST_ASSIGN_DATA_REQUEST";
export const OANDM_BLOCK_SCRAP_REQUEST_ASSIGN_DATA_SUCCESS =
  "OANDM_BLOCK_SCRAP_REQUEST_ASSIGN_DATA_SUCCESS";
export const OANDM_BLOCK_SCRAP_REQUEST_ASSIGN_DATA_FAILED =
  "OANDM_BLOCK_SCRAP_REQUEST_ASSIGN_DATA_FAILED";

// GP
//Maintainace
//Maintenance request
export const OANDM_GP_MAINTENANCE_REQUEST_DATA_REQUEST =
  "OANDM_GP_MAINTENANCE_REQUEST_DATA_REQUEST";
export const OANDM_GP_MAINTENANCE_REQUEST_DATA_SUCCESS =
  "OANDM_GP_MAINTENANCE_REQUEST_DATA_SUCCESS";
export const OANDM_GP_MAINTENANCE_REQUEST_DATA_FAILED =
  "OANDM_GP_MAINTENANCE_REQUEST_DATA_FAILED";
//request assign
export const OANDM_GP_MAINTENANCE_REQUEST_ASSIGN_DATA_REQUEST =
  "OANDM_GP_MAINTENANCE_REQUEST_ASSIGN_DATA_REQUEST";
export const OANDM_GP_MAINTENANCE_REQUEST_ASSIGN_DATA_SUCCESS =
  "OANDM_GP_MAINTENANCE_REQUEST_ASSIGN_DATA_SUCCESS";
export const OANDM_GP_MAINTENANCE_REQUEST_ASSIGN_DATA_FAILED =
  "OANDM_GP_MAINTENANCE_REQUEST_ASSIGN_DATA_FAILED";

//Replacement
//Replacement request
export const OANDM_GP_REPLACEMENT_REQUEST_DATA_REQUEST =
  "OANDM_GP_REPLACEMENT_REQUEST_DATA_REQUEST";
export const OANDM_GP_REPLACEMENT_REQUEST_DATA_SUCCESS =
  "OANDM_GP_REPLACEMENT_REQUEST_DATA_SUCCESS";
export const OANDM_GP_REPLACEMENT_REQUEST_DATA_FAILED =
  "OANDM_GP_REPLACEMENT_REQUEST_DATA_FAILED";
//request assign
export const OANDM_GP_REPLACEMENT_REQUEST_ASSIGN_DATA_REQUEST =
  "OANDM_GP_REPLACEMENT_REQUEST_ASSIGN_DATA_REQUEST";
export const OANDM_GP_REPLACEMENT_REQUEST_ASSIGN_DATA_SUCCESS =
  "OANDM_GP_REPLACEMENT_REQUEST_ASSIGN_DATA_SUCCESS";
export const OANDM_GP_REPLACEMENT_REQUEST_ASSIGN_DATA_FAILED =
  "OANDM_GP_REPLACEMENT_REQUEST_ASSIGN_DATA_FAILED";

//Transfer
//Transfer request
export const OANDM_GP_TRANSFER_REQUEST_DATA_REQUEST =
  "OANDM_GP_TRANSFER_REQUEST_DATA_REQUEST";
export const OANDM_GP_TRANSFER_REQUEST_DATA_SUCCESS =
  "OANDM_GP_TRANSFER_REQUEST_DATA_SUCCESS";
export const OANDM_GP_TRANSFER_REQUEST_DATA_FAILED =
  "OANDM_GP_TRANSFER_REQUEST_DATA_FAILED";
//request assign
export const OANDM_GP_TRANSFER_REQUEST_ASSIGN_DATA_REQUEST =
  "OANDM_GP_TRANSFER_REQUEST_ASSIGN_DATA_REQUEST";
export const OANDM_GP_TRANSFER_REQUEST_ASSIGN_DATA_SUCCESS =
  "OANDM_GP_TRANSFER_REQUEST_ASSIGN_DATA_SUCCESS";
export const OANDM_GP_TRANSFER_REQUEST_ASSIGN_DATA_FAILED =
  "OANDM_GP_TRANSFER_REQUEST_ASSIGN_DATA_FAILED";

//Scrap
//Scrap request
export const OANDM_GP_SCRAP_REQUEST_DATA_REQUEST =
  "OANDM_GP_SCRAP_REQUEST_DATA_REQUEST";
export const OANDM_GP_SCRAP_REQUEST_DATA_SUCCESS =
  "OANDM_GP_SCRAP_REQUEST_DATA_SUCCESS";
export const OANDM_GP_SCRAP_REQUEST_DATA_FAILED =
  "OANDM_GP_SCRAP_REQUEST_DATA_FAILED";
//request assign
export const OANDM_GP_SCRAP_REQUEST_ASSIGN_DATA_REQUEST =
  "OANDM_GP_SCRAP_REQUEST_ASSIGN_DATA_REQUEST";
export const OANDM_GP_SCRAP_REQUEST_ASSIGN_DATA_SUCCESS =
  "OANDM_GP_SCRAP_REQUEST_ASSIGN_DATA_SUCCESS";
export const OANDM_GP_SCRAP_REQUEST_ASSIGN_DATA_FAILED =
  "OANDM_GP_SCRAP_REQUEST_ASSIGN_DATA_FAILED";

