//assets
export const HOTO_WAREHOUSE_ASSETS_DATA_REQUEST = "HOTO_WAREHOUSE_ASSETS_DATA_REQUEST";
export const HOTO_WAREHOUSE_ASSETS_DATA_SUCCESS = "HOTO_WAREHOUSE_ASSETS_DATA_SUCCESS";
export const HOTO_WAREHOUSE_ASSETS_DATA_FAILED = "HOTO_WAREHOUSE_ASSETS_DATA_FAILED";

// inward assets
export const HOTO_WAREHOUSE_INWARD_ASSETS_DATA_REQUEST =
  "HOTO_WAREHOUSE_INWARD_ASSETS_DATA_REQUEST";
export const HOTO_WAREHOUSE_INWARD_ASSETS_DATA_SUCCESS =
  "HOTO_WAREHOUSE_INWARD_ASSETS_DATA_SUCCESS";
export const HOTO_WAREHOUSE_INWARD_ASSETS_DATA_FAILED =
  "HOTO_WAREHOUSE_INWARD_ASSETS_DATA_FAILED";

// Maintenance
export const HOTO_WAREHOUSE_MAINTENANCE_DATA_REQUEST =
  "HOTO_WAREHOUSE_MAINTENANCE_DATA_REQUEST";
export const HOTO_WAREHOUSE_MAINTENANCE_DATA_SUCCESS =
  "HOTO_WAREHOUSE_MAINTENANCE_DATA_SUCCESS";
export const HOTO_WAREHOUSE_MAINTENANCE_DATA_FAILED =
  "HOTO_WAREHOUSE_MAINTENANCE_DATA_FAILED";

// transfer
export const HOTO_WAREHOUSE_TRANSFER_DATA_REQUEST =
  "HOTO_WAREHOUSE_TRANSFER_DATA_REQUEST";
export const HOTO_WAREHOUSE_TRANSFER_DATA_SUCCESS =
  "HOTO_WAREHOUSE_TRANSFER_DATA_SUCCESS";
export const HOTO_WAREHOUSE_TRANSFER_DATA_FAILED =
  "HOTO_WAREHOUSE_TRANSFER_DATA_FAILED";

//replacement
  export const HOTO_WAREHOUSE_REPLACEMENT_DATA_REQUEST =
    "HOTO_WAREHOUSE_REPLACEMENT_DATA_REQUEST";
  export const HOTO_WAREHOUSE_REPLACEMENT_DATA_SUCCESS =
    "HOTO_WAREHOUSE_REPLACEMENT_DATA_SUCCESS";
  export const HOTO_WAREHOUSE_REPLACEMENT_DATA_FAILED =
    "HOTO_WAREHOUSE_REPLACEMENT_DATA_FAILED";