//assets
export const OUT_HOTO_WAREHOUSE_ASSETS_DATA_REQUEST = "OUT_HOTO_WAREHOUSE_ASSETS_DATA_REQUEST";
export const OUT_HOTO_WAREHOUSE_ASSETS_DATA_SUCCESS = "OUT_HOTO_WAREHOUSE_ASSETS_DATA_SUCCESS";
export const OUT_HOTO_WAREHOUSE_ASSETS_DATA_FAILED = "OUT_HOTO_WAREHOUSE_ASSETS_DATA_FAILED";

// inward assets
export const OUT_HOTO_WAREHOUSE_INWARD_ASSETS_DATA_REQUEST =
  "OUT_HOTO_WAREHOUSE_INWARD_ASSETS_DATA_REQUEST";
export const OUT_HOTO_WAREHOUSE_INWARD_ASSETS_DATA_SUCCESS =
  "OUT_HOTO_WAREHOUSE_INWARD_ASSETS_DATA_SUCCESS";
export const OUT_HOTO_WAREHOUSE_INWARD_ASSETS_DATA_FAILED =
  "OUT_HOTO_WAREHOUSE_INWARD_ASSETS_DATA_FAILED";

// Maintenance
export const OUT_HOTO_WAREHOUSE_MAINTENANCE_DATA_REQUEST =
  "OUT_HOTO_WAREHOUSE_MAINTENANCE_DATA_REQUEST";
export const OUT_HOTO_WAREHOUSE_MAINTENANCE_DATA_SUCCESS =
  "OUT_HOTO_WAREHOUSE_MAINTENANCE_DATA_SUCCESS";
export const OUT_HOTO_WAREHOUSE_MAINTENANCE_DATA_FAILED =
  "OUT_HOTO_WAREHOUSE_MAINTENANCE_DATA_FAILED";

// transfer
export const OUT_HOTO_WAREHOUSE_TRANSFER_DATA_REQUEST =
  "OUT_HOTO_WAREHOUSE_TRANSFER_DATA_REQUEST";
export const OUT_HOTO_WAREHOUSE_TRANSFER_DATA_SUCCESS =
  "OUT_HOTO_WAREHOUSE_TRANSFER_DATA_SUCCESS";
export const OUT_HOTO_WAREHOUSE_TRANSFER_DATA_FAILED =
  "OUT_HOTO_WAREHOUSE_TRANSFER_DATA_FAILED";

//replacement
  export const OUT_HOTO_WAREHOUSE_REPLACEMENT_DATA_REQUEST =
    "OUT_HOTO_WAREHOUSE_REPLACEMENT_DATA_REQUEST";
  export const OUT_HOTO_WAREHOUSE_REPLACEMENT_DATA_SUCCESS =
    "OUT_HOTO_WAREHOUSE_REPLACEMENT_DATA_SUCCESS";
  export const OUT_HOTO_WAREHOUSE_REPLACEMENT_DATA_FAILED =
    "OUT_HOTO_WAREHOUSE_REPLACEMENT_DATA_FAILED";