//Warehouse 
//Daily stock
export const OANDM_WAREHOUSE_DAILYSTOCK_DATA_REQUEST =
  "OANDM_WAREHOUSE_DAILYSTOCK_DATA_REQUEST";
export const OANDM_WAREHOUSE_DAILYSTOCK_DATA_SUCCESS =
  "OANDM_WAREHOUSE_DAILYSTOCK_DATA_SUCCESS";
export const OANDM_WAREHOUSE_DAILYSTOCK_DATA_FAILED =
  "OANDM_WAREHOUSE_DAILYSTOCK_DATA_FAILED";
// Stock
export const OANDM_WAREHOUSE_STOCK_DATA_REQUEST = "OANDM_WAREHOUSE_STOCK_DATA_REQUEST";
export const OANDM_WAREHOUSE_STOCK_DATA_SUCCESS = "OANDM_WAREHOUSE_STOCK_DATA_SUCCESS";
export const OANDM_WAREHOUSE_STOCK_DATA_FAILED = "OANDM_WAREHOUSE_STOCK_DATA_FAILED";
//Virtual Stock
export const OANDM_WAREHOUSE_VIRTUALSTOCK_DATA_REQUEST =
  "OANDM_WAREHOUSE_VIRTUALSTOCK_DATA_REQUEST";
export const OANDM_WAREHOUSE_VIRTUALSTOCK_DATA_SUCCESS =
  "OANDM_WAREHOUSE_VIRTUALSTOCK_DATA_SUCCESS";
export const OANDM_WAREHOUSE_VIRTUALSTOCK_DATA_FAILED =
  "OANDM_WAREHOUSE_VIRTUALSTOCK_DATA_FAILED";

//Material Request
//Open Request
export const OANDM_MARERIALREQUEST_OPENREQUEST_DATA_REQUEST =
  "OANDM_MARERIALREQUEST_OPENREQUEST_DATA_REQUEST";
export const OANDM_MARERIALREQUEST_OPENREQUEST_DATA_SUCCESS =
  "OANDM_MARERIALREQUEST_OPENREQUEST_DATA_SUCCESS";
export const OANDM_MARERIALREQUEST_OPENREQUEST_DATA_FAILED =
  "OANDM_MARERIALREQUEST_OPENREQUEST_DATA_FAILED";
// Request Log
export const OANDM_MARERIALREQUEST_REQUESTLOG_DATA_REQUEST =
  "OANDM_MARERIALREQUEST_REQUESTLOG_DATA_REQUEST";
export const OANDM_MARERIALREQUEST_REQUESTLOG_DATA_SUCCESS =
  "OANDM_MARERIALREQUEST_REQUESTLOG_DATA_SUCCESS";
export const OANDM_MARERIALREQUEST_REQUESTLOG_DATA_FAILED =
  "OANDM_MARERIALREQUEST_REQUESTLOG_DATA_FAILED";


// Material Inward
// GRN List
export const OANDM_MARERIALINWARD_GRN_DATA_REQUEST =
  "OANDM_MARERIALINWARD_GRN_DATA_REQUEST";
export const OANDM_MARERIALINWARD_GRN_DATA_SUCCESS =
  "OANDM_MARERIALINWARD_GRN_DATA_SUCCESS";
export const OANDM_MARERIALINWARD_GRN_DATA_FAILED =
  "OANDM_MARERIALINWARD_GRN_DATA_FAILED";
// Inward Item List
export const OANDM_MARERIALINWARD_INWARDITEM_DATA_REQUEST =
  "OANDM_MARERIALINWARD_INWARDITEM_DATA_REQUEST";
export const OANDM_MARERIALINWARD_INWARDITEM_DATA_SUCCESS =
  "OANDM_MARERIALINWARD_INWARDITEM_DATA_SUCCESS";
export const OANDM_MARERIALINWARD_INWARDITEM_DATA_FAILED =
  "OANDM_MARERIALINWARD_INWARDITEM_DATA_FAILED";